# Dockerfile (producción)

### Etapa 1: Build ###
FROM node:20.11.1-bullseye-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build


### Etapa 2: Servidor web ###
FROM nginx:1.27-alpine

# Copiamos el build estático
COPY --from=builder /app/dist /usr/share/nginx/html

# Nginx ya expone el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
