"""
Django settings for lsq project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ON_PRODUCTION = config('ON_PRODUCTION', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# NGROK
NGROK_ENABLE = config('NGROK_ENABLE', default=False, cast=bool)
if NGROK_ENABLE:
    NGROK_WEB = config('NGROK_WEB')
    NGROK_HOST = config('NGROK_HOST')
    X_FRAME_OPTIONS = f'ALLOW-FROM {NGROK_WEB}'
    CSRF_TRUSTED_ORIGINS = [NGROK_WEB]
    ALLOWED_HOSTS.append(NGROK_HOST)
else:
    X_FRAME_OPTIONS = 'SAMEORIGIN'

# Nombre del dominio
WEB_NAME = config('WEB_NAME')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Mis apps
    'genera3d',
    # Apps de terceros
    'django_celery_results',
    'django_celery_beat',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Lista blanca de orígenes permitidos
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://frontend:5173",
]
# Producción (añadir tu dominio)
if ON_PRODUCTION:
    CORS_ALLOWED_ORIGINS = [
        f'https://${WEB_NAME}',
    ]

ROOT_URLCONF = 'lsq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'lsq.context_processors.settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'lsq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Español')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# AMAZON AWS S3
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

DEFAULT_FILE_STORAGE = 'lsq.storage_backends.PrivateMediaStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
if ON_PRODUCTION:
    STATIC_ROOT = config('STATIC_ROOT')
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
    STATICFILES_MANIFEST_STRICT = False
else:
    STATICFILES_DIRS = [
        BASE_DIR / 'static',
    ]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / MEDIA_URL[1:]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if ON_PRODUCTION:
    CSRF_COOKIE_SAMESITE = None
    CSRF_COOKIE_SECURE = True

# Logs

if ON_PRODUCTION:
    LOG_DIR = config('LOG_DIR')
    
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'django_file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': f'{LOG_DIR}/django.log',
                'formatter': 'verbose',
            },
            'celery_file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': f'{LOG_DIR}/celery.log',
                'formatter': 'verbose',
            },
            'aws_file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': f'{LOG_DIR}/aws.log',
                'formatter': 'verbose',
            },
            'stripe_file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': f'{LOG_DIR}/stripe.log',
                'formatter': 'verbose',
            },
            'mail_admins': {
                'level': 'ERROR',
                'class': 'django.utils.log.AdminEmailHandler',
                'formatter': 'verbose',
                'include_html': True,
            },
            'null': {
                'level': 'DEBUG',
                'class': 'logging.NullHandler',
            },
        },
        'loggers': {
            'django.security.DisallowedHost': {
                'handlers': ['null'],
                'propagate': False,
            },
            'django': {
                'handlers': ['django_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'celery': {
                'handlers': ['celery_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'celery.task': {
                'handlers': ['celery_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'boto3': {
                'handlers': ['aws_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'botocore': {
                'handlers': ['aws_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'boto3.resources': {
                'handlers': ['aws_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'botocore.credentials': {
                'handlers': ['aws_file'],
                'level': 'ERROR',
                'propagate': False,
            },
            'stripe': {
                'handlers': ['stripe_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            '': {
                'handlers': ['django_file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'celery': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'celery.task': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
            'boto3': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'botocore': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
            's3transfer': {
                'handlers': ['console'],
                'level': 'WARNING',
                'propagate': False,
            },
            'stripe': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# ====================
# MODO MANTENIMIENTO
# ====================
# Cambiar a True para activar el modo mantenimiento
# Esto mostrará una página de mantenimiento a TODOS los usuarios
# TODO: Cambiar para que se pueda activar/desactivar desde el admin de Django
MAINTENANCE_MODE = config('MAINTENANCE_MODE', default=False, cast=bool)